export const LOADING = "LOADING";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const ROOM_REQUEST = "ROOM_REQUEST";
export const ROOM_REQUEST_SUCCESS = "ROOM_REQUEST_SUCCESS";
export const ROOM_REQUEST_FAIL = "ROOM_REQUEST_FAIL"
export const SET_CLICKED_ROOM = "SET_CLICKED_ROOM";

export const LOCATION_REQUEST = "LOCATION_REQUEST"
export const LOCATION_REQUEST_SUCCESS = "LOCATION_REQUEST_SUCCESS"
export const LOCATION_REQUEST_FAIL = "LOCATION_REQUEST_FAIL"


